### ISSUE TITLE
Add retry mechanisms for failed onward processing

### ISSUE THREAD

**Issue by rickpowell1311** [rickpowell1311/onwrd#10]
Using `IOnwardProcessor` can throw exceptions for many reasons (this is designed to execute custom code built by consumers of the Onwrd package). If there any issues with this, we should allow consuming code to define exactly how (if it all) onward processing should be retried.

There are several different factors to consider when working with retries:
1. Should onward processing be carried out in the order the original attempts were invoked
2. In what context should the retries execute? In a long-running background task? If not, what other options are there?
3. Based on the above decision, should the initial onward processing attempt continue to be processed inline with a request, or as a background task along with other retries?

Current thoughts:

1. Onwrd is designed to work in conjunction with other messaging libraries that can be configured to process messages in order or not. If Onwrd doesn't comply with in-order message execution, then this invalidates any onward processing that could otherwise have occurred in order. As a first pass for a retry mechanism, we'll only allow retries to be processed in order. 
2. Retres can either be invoked by code managed by Onwrd, or by code managed by the consumer. Both have their own benefits. If Onwrd manages the invocation of retries, there is a limitation of the context in which they can run (most likely on a background thread, where lifetime is at the mercy of the executing environment). As an example, this could be suitable in subscription-based services, but not in consumption-based services. If the consuming code manages the invocation of retires, then there's more work for consuming code to do, and the exposure of retry APIs from Onwrd needs to be carefully considered. The most likely solution here is to be as explicit as possible in the configuration of retries, most likely using Onwrd-managed background-thread retries by default, but having the option of switching retires off, and exposing an API to be able to invoke them.
3. Initial attempts at onward processing are currently part of the same process as the original application request (in-process). This may come with a performance penalty, given that slow performance of an `IOnwrdProcessor` would also result in slow response times for the original request. Similarly to the above, the requirements for in-process onward processing depends entirely on the executing environment. In consumption-based environments, we'd want onward processing to be made inline with the request, and it's up to the consuming code to ensure the execution is snappy. For subscription-based environments, delegating work to the background thread should be an option.

Example APIs for consumers.

Configuration:
```
services.AddDbContext<MyContext>(
            (serviceProvider, builder) =>
            {
                supportedDatabase.UseInMemoryDatabase("MyContext");
            },
            onwrdConfig =>
            {
                onwrdConfig.UseOnwardProcessor<TestOnwardProcessor>();

                /* Environment can be Consumption or Subscription. Consumption will invoke `IOnwardProcessor` in-line with the request and retries will need to be manually invoked (see below). Subscription will invoke `IOnwardProcessor` and all successive retries on a background-thread. */
                onwrdConfig.ForEnvironment(Environment.Consumption); 

                /* no config would use default settings. Not configuring at all would end up with the same result. Retry options apply regardless of whether retries are carried out in the background or not. */
                onwrdConfig.ConfigureRetryOptions(retries =>
                {
                    retries.Attempts = Attempts.Finite(5); // can be infinite
                    retries.Poll = TimeSpan.FromSeconds(5) // indicates the minimum time between polling for new onwrd messages to process
                }); 
                // other config...
            });
```

Custom retries
```
IOnwrdRetryManager retryManager;
CancellationToken token;

/* Invokes retries as a long-running task. `IOnwrdRetryManager` will be registered as part of the ServiceCollection when the Onwrd overload of `AddDbContext` is called. Will continue execution indefinitely, so cancellation token provided for graceful shutdown */
await retryManager.RetryOnwardProcessing(token); 
```

**Comment by rickpowell1311** [comment]
Because the `IOnwardProcessor ` has a `Process<TEvent>(TEvent @event)` method, we need to be able to deserialize the stored contents of the event back to it's originating type before invoking this method.

**Comment by rickpowell1311** [comment]
Implementing the consumption pattern for retries first will be easier because there's no multi-threading required.

**Comment by rickpowell1311** [comment]
Have implemented this without a distinction between consumption and subscription-based environments. For now, retries will always need to be managed by the client by calling the `IOnwardRetryManager<TContext>.RetryOnwardProcessing(CancellationToken cancellationToken = default)` method.

Final configuration looks like this:

```
services.AddDbContext<MyContext>(
            (serviceProvider, builder) =>
            {
                supportedDatabase.UseInMemoryDatabase("MyContext");
            },
            onwrdConfig =>
            {
                onwrdConfig.UseOnwardProcessor<MyOnwardProcessor>();
                onwrdConfig.ConfigureRetryOptions(retries =>
                {
                    retries.Attempts = 5; // up to int.MaxValue;
                    retries.PollPeriod = TimeSpan.FromSeconds(5) // indicates the minimum time between polling for new onwrd events to process, after no events were found.
                    retries.RetryAfter(TimeSpan.FromSeconds(10)); // indicates the waiting time between attempts for processing events
                }); 
                // other config...
            });

**Comment by rickpowell1311** [comment]
Closing the issue, with a view to re-opening if there is a requirement for background processing of retries and the initial onward processing attempt

**Comment by lorna-propelle** [comment]
Noice 😁
