### ISSUE TITLE
Onward processing for non-generic domain event types

### ISSUE THREAD

**Issue by rick-propelle** [rickpowell1311/onwrd#15]
**Summary**

Using `IOnwrdProcessor.Process<T>(T @event, EventMetadata eventMetadata)` is limited because consumer-processing logic will differ depending on the type of event that has been raised. A more consumer-friendly entry point for onward processing would be to work with non-generic domain event types.

I can see 2 different approaches for this:

1. Expose a completely separate `IOnwrdProcessor<T>.Process(T @event, EventMetadata eventMetadata)`, where types of `IOnwrdProcessor<T>` can be registered as part of the DI configuration. 

2. Expose a separate task management layer that the original `IOnwrdProcessor.Process<T>(T @event, EventMetadata eventMetadata) method can call. For example:

```
public interface IOnwrdTask<TEvent>
{
    Task Process(TEvent @event)
}
```

```
public interface IOnwrdTaskManager
{
    Task<bool> RunTasksFor<TEvent>(TEvent @event)
}
```

```
public class MyOnwardProcessor : IOnwrdProcessor
{
    private readonly IOnwrdTaskManager _taskManager;
    
    public MyOnwardProcessor(IOnwrdTaskManager taskManager)
    {
        _taskManager = taskManager;
    }

    public Task Process<T>(T @event, EventMetadata eventMetadata)
    {
        _taskManager.RunTasksFor(@event);
    }
}
```

The 1st approach is preferred to the 2nd, given the simplicity and exclusion of boiler plate code required by consumers. 
The 2nd approach is more explicit, but has the advantage of the client code being able to customize the interaction with tasks for a specific event.

Taking the 1st approach, the configuration may look something like this:

```
services.AddDbContext<MyContext>(
    (serviceProvider, builder) =>
    {
        // ...
    },
    onwrdConfig => 
    {
        // Outboxing configuration here
        onwrdConfig.UseOnwardProcessor<MyOnwardProcessor>(); // No changes here
        onwrdConfig.UseOnwardProcessors(cfg => 
        {
             cfg.ScanAssembly(typeof(this).Assembly); // Example of using assembly scanning to find implementations
             cfg.Register<TEvent, TProcessor>(); // where TProcessor : IOnwrdProcessor<TEvent>(). Example of adding individual implementation
        }
    });
```
    
When a type-specific event processor is registered (either through assembly scanning or explicitly), the default onward processor will not be executed. In this sense, if the type-specific event processor wants to share functionality that exists in the default processor, it is up to the consuming code to manage.

**Comment by rick-propelle** [comment]
When it comes to retries, by deafult the order of processing should be respected across all event types.

**Comment by rickpowell1311** [comment]
Given that the functionality of the framework as a result of registering either `onwrdConfig.UseOnwardProcessor<T>()` or `onwrdConfig.UseOnwardProcessors()` methods is mutually exclusive, a "last registration wins" behaviour will be adopted

**Comment by rickpowell1311** [comment]
Although multiple onward processors processing the same type of event is going to be supported, there will be no guarantee of order, nor any guarantee of idempotent processing. This is to keep the initial implementation light, but also a recognition of the fact that no onward processing will ever be guaranteed to be idempotent, given the potential transient issue of completing the onward processing but not being able to record that onward processing completed at any time.

**Comment by rickpowell1311** [comment]
https://github.com/rickpowell1311/onwrd/pull/17
